licensingservice:
  image: ch3-thoughtmechanix/licensing-service
  ports:
   - "8080:8080"
  environment:
    PROFILE: "default"
    CONFIGSERVER_URI: http://localhost:8888
    CONFIGSERVER_PORT: "8888"
    DATABASESERVER_PORT: "5432"
